import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'project_team': 'Project Team',
    'smart_calendar': 'Smart Calendar',
    'finance_budget': 'Finance & Budget',
    '3d_viewer': '3D Viewer (BIM)',
    'meet_chat': 'Meet & Chat',
    'crm_docs': 'CRM & Docs',
    'document_hub': 'Document Hub',
    'site_monitoring': 'Site Monitoring',
    'audio_whiteboard': 'Audio & Whiteboard',
    'pitch_deck': 'Pitch Deck',
    'defects': 'Defects',
    'api_roadmap': 'API & Roadmap',
    'logout': 'Logout',
    'search': 'Search...',
    'help': 'Help Center',
    'settings': 'Settings',
    'back_to_projects': 'Back to Projects',
    'select_project': 'Select Project',
    'no_status': 'No status',
    'admin_dashboard': 'Admin Dashboard',
    'company_dashboard': 'Company Dashboard',
    'welcome_back': 'Welcome back',
    'active_projects': 'Active Projects',
    'total_budget': 'Total Budget',
    'team_members': 'Team Members',
    'recent_activity': 'Recent Activity',
    // Meet & Chat
    'video_call': 'Video Call',
    'chat': 'Chat',
    'end_call': 'End Call',
    'mute': 'Mute',
    'unmute': 'Unmute',
    'video_off': 'Video Off',
    'video_on': 'Video On',
    'share_screen': 'Share Screen',
    'type_message': 'Type a message... (Use @AI to ask the Concierge)',
    'send': 'Send',
    // Pitch Deck
    'templates': 'Templates',
    'add_slide': 'Add Slide',
    'export_pdf': 'Export PDF',
    'title_slide': 'Title Slide',
    'content_slide': 'Content Slide',
    'image_slide': 'Image Slide',
    'budget_slide': 'Budget Slide',
    'timeline_slide': 'Timeline Slide',
    'empty_deck': 'Your pitch deck is empty. Add a slide to get started.',
    'slide': 'Slide',
    'of': 'of',
    // Company Dashboard
    'projects': 'Projects',
    'team': 'Team',
    'documents': 'Documents',
    'leads': 'Leads',
    'timesheets': 'Timesheets',
    'new_project': 'New Project',
    'new_user': 'New User',
    'status': 'Status',
    'role': 'Role',
    'planning': 'Planning',
    'active': 'Active',
    'completed': 'Completed',
    'on_hold': 'On Hold',
    'owner': 'Owner',
    'admin': 'Admin',
    'member': 'Member',
    'guest': 'Guest',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'name': 'Name',
    'email': 'Email',
    'department': 'Department',
    'hourly_rate': 'Hourly Rate',
    // Admin Dashboard
    'analytics_overview': 'Analytics & Overview',
    'user_management': 'User Management',
    'orders': 'Orders',
    'quotes': 'Quotes',
    'tasks': 'Tasks',
    'permissions': 'Permissions',
    'billing_subscriptions': 'Billing & Subscriptions',
    'system_logs': 'System Logs',
    'total_users': 'Total Users',
    'storage_used': 'Storage Used',
    'revenue': 'Revenue',
    'new_users': 'New Users',
    // Dashboard
    'project_overview': 'Project Overview',
    'loading_project': 'Loading Project...',
    'on_track': 'On Track',
    'completed_percent': 'Completed',
    'ai_concierge_insights': 'AI Concierge Insights',
    'live_analysis': 'Live Analysis',
    'budget_discrepancy': 'Budget Discrepancy Detected',
    'schedule_shift': 'Schedule Shift Warning',
    'review_ai_suggestions': 'Review AI Suggestions',
    'daily_tasks': 'Daily Tasks',
    'view_all_tasks': 'View All Tasks',
    'all_tasks': 'All Tasks',
    'priority': 'Priority',
    'due_date': 'Due Date',
    'assignee': 'Assignee',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'to_do': 'To Do',
    'done': 'Done',
    'budget_overview': 'Budget Overview',
    'hours_overview': 'Hours Overview',
    'open_defects': 'Open Defects',
    'bim_revisions': 'BIM Revisions',
    'project_participants': 'Project Participants & Freelancers',
    'manage_team': 'Manage Team',
    'recent_documents': 'Recent Documents',
    'view_all_docs': 'View All Docs',
    'recent_activity_log': 'Recent Activity Log',
    'view_full_log': 'View Full Log',
    'upcoming_deadlines': 'Upcoming Deadlines',
    'quick_actions': 'Quick Actions',
    'project_initialized': 'Project initialized',
    'just_now': 'Just now',
    'project_kickoff': 'Project Kickoff',
    'tbd': 'TBD',
    'upload_floor_plan': 'Upload Floor Plan (DWG)',
    'generate_client_pitch_deck': 'Generate Client Pitch Deck',
    'schedule_site_meeting': 'Schedule Site Meeting',
    'live_collaboration': 'Live Collaboration',
    'weekly_coordination': 'Weekly Coordination Meeting',
    'schedule_call': 'Schedule Call',
    'ai_summary': 'AI Summary',
    'leave_call': 'Leave Call',
    'join_call': 'Join Call',
    'video': 'Video',
    'whiteboard': 'Whiteboard',
    '3d_model': '3D Model',
    'ready_to_join': 'Ready to join?',
    'join_weekly_meeting': 'Join the weekly coordination meeting',
    '3d_model_sync': '3D Model Sync',
    'bim_viewer_sync': 'BIM Viewer synchronized with Mark Smith. You are seeing their perspective.',
    'project_chat': 'Project Chat',
    'schedule_video_call': 'Schedule Video Call',
    'meeting_title': 'Meeting Title',
    'date': 'Date',
    'time': 'Time',
    'meeting_type': 'Meeting Type',
    'description': 'Description',
    'schedule': 'Schedule',
  },
  de: {
    'dashboard': 'Übersicht',
    'project_team': 'Projektteam',
    'smart_calendar': 'Terminpläne',
    'finance_budget': 'Finanzen & Kalkulation',
    '3d_viewer': '3D Viewer (BIM)',
    'meet_chat': 'Live Kollaboration',
    'crm_docs': 'Dokumente & Kontakte',
    'document_hub': 'Dokumenten-Hub',
    'site_monitoring': 'Baustellenüberwachung',
    'audio_whiteboard': 'Audio & Whiteboard',
    'pitch_deck': 'Pitch Deck',
    'defects': 'Mängelmanagement',
    'api_roadmap': 'API & Roadmap',
    'logout': 'Abmelden',
    'search': 'Suchen...',
    'help': 'Hilfe-Center',
    'settings': 'Einstellungen',
    'back_to_projects': 'Zurück zu Projekten',
    'select_project': 'Projekt auswählen',
    'no_status': 'Kein Status',
    'admin_dashboard': 'Admin-Dashboard',
    'company_dashboard': 'Unternehmens-Dashboard',
    'welcome_back': 'Willkommen zurück',
    'active_projects': 'Aktive Projekte',
    'total_budget': 'Gesamtbudget',
    'team_members': 'Teammitglieder',
    'recent_activity': 'Letzte Aktivitäten',
    // Meet & Chat
    'video_call': 'Videoanruf',
    'chat': 'Chat',
    'end_call': 'Anruf beenden',
    'mute': 'Stummschalten',
    'unmute': 'Stummschaltung aufheben',
    'video_off': 'Video aus',
    'video_on': 'Video an',
    'share_screen': 'Bildschirm teilen',
    'type_message': 'Nachricht tippen... (@AI für den Concierge)',
    'send': 'Senden',
    // Pitch Deck
    'templates': 'Vorlagen',
    'add_slide': 'Folie hinzufügen',
    'export_pdf': 'PDF exportieren',
    'title_slide': 'Titelfolie',
    'content_slide': 'Inhaltsfolie',
    'image_slide': 'Bildfolie',
    'budget_slide': 'Budgetfolie',
    'timeline_slide': 'Zeitplanfolie',
    'empty_deck': 'Ihr Pitch Deck ist leer. Fügen Sie eine Folie hinzu, um zu beginnen.',
    'slide': 'Folie',
    'of': 'von',
    // Company Dashboard
    'projects': 'Projekte',
    'team': 'Team',
    'documents': 'Dokumente',
    'leads': 'Leads',
    'timesheets': 'Zeiterfassung',
    'new_project': 'Neues Projekt',
    'new_user': 'Neuer Benutzer',
    'status': 'Status',
    'role': 'Rolle',
    'planning': 'Planung',
    'active': 'Aktiv',
    'completed': 'Abgeschlossen',
    'on_hold': 'Pausiert',
    'owner': 'Eigentümer',
    'admin': 'Admin',
    'member': 'Mitglied',
    'guest': 'Gast',
    'edit': 'Bearbeiten',
    'delete': 'Löschen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'name': 'Name',
    'email': 'E-Mail',
    'department': 'Abteilung',
    'hourly_rate': 'Stundensatz',
    // Admin Dashboard
    'analytics_overview': 'Analytics & Übersicht',
    'user_management': 'Benutzerverwaltung',
    'orders': 'Bestellungen',
    'quotes': 'Offerten',
    'tasks': 'Aufgaben',
    'permissions': 'Berechtigungen',
    'billing_subscriptions': 'Abrechnung & Abos',
    'system_logs': 'Systemprotokolle',
    'total_users': 'Benutzer gesamt',
    'storage_used': 'Speicherplatz genutzt',
    'revenue': 'Umsatz',
    'new_users': 'Neue Benutzer',
    // Dashboard
    'project_overview': 'Projektübersicht',
    'loading_project': 'Projekt wird geladen...',
    'on_track': 'Im Zeitplan',
    'completed_percent': 'Abgeschlossen',
    'ai_concierge_insights': 'AI Concierge Erkenntnisse',
    'live_analysis': 'Live-Analyse',
    'budget_discrepancy': 'Budgetabweichung erkannt',
    'schedule_shift': 'Zeitplanverschiebung Warnung',
    'review_ai_suggestions': 'KI-Vorschläge prüfen',
    'daily_tasks': 'Tagesaufgaben',
    'view_all_tasks': 'Alle Aufgaben anzeigen',
    'all_tasks': 'Alle Aufgaben',
    'priority': 'Priorität',
    'due_date': 'Fälligkeitsdatum',
    'assignee': 'Zuständig',
    'high': 'Hoch',
    'medium': 'Mittel',
    'low': 'Niedrig',
    'to_do': 'Zu erledigen',
    'done': 'Erledigt',
    'budget_overview': 'Budget Übersicht',
    'hours_overview': 'Stunden Übersicht',
    'open_defects': 'Offene Mängel',
    'bim_revisions': 'BIM Revisionen',
    'project_participants': 'Planer & Projektbeteiligte (Freelancer)',
    'manage_team': 'Team verwalten',
    'recent_documents': 'Aktuelle Dokumente',
    'view_all_docs': 'Alle Dokumente',
    'recent_activity_log': 'Aktivitätenprotokoll',
    'view_full_log': 'Gesamtes Protokoll',
    'upcoming_deadlines': 'Anstehende Fristen',
    'quick_actions': 'Schnellaktionen',
    'project_initialized': 'Projekt initialisiert',
    'just_now': 'Gerade eben',
    'project_kickoff': 'Projekt Kickoff',
    'tbd': 'TBD',
    'upload_floor_plan': 'Grundriss hochladen (DWG)',
    'generate_client_pitch_deck': 'Kunden Pitch Deck erstellen',
    'schedule_site_meeting': 'Baustellenbesprechung planen',
    'live_collaboration': 'Live-Kollaboration',
    'weekly_coordination': 'Wöchentliches Koordinationsmeeting',
    'schedule_call': 'Anruf planen',
    'ai_summary': 'KI-Zusammenfassung',
    'leave_call': 'Anruf verlassen',
    'join_call': 'Anruf beitreten',
    'video': 'Video',
    'whiteboard': 'Whiteboard',
    '3d_model': '3D-Modell',
    'ready_to_join': 'Bereit beizutreten?',
    'join_weekly_meeting': 'Nehmen Sie am wöchentlichen Koordinationsmeeting teil',
    '3d_model_sync': '3D-Modell-Synchronisation',
    'bim_viewer_sync': 'BIM-Viewer mit Mark Smith synchronisiert. Sie sehen seine Perspektive.',
    'project_chat': 'Projekt-Chat',
    'schedule_video_call': 'Videoanruf planen',
    'meeting_title': 'Titel des Meetings',
    'date': 'Datum',
    'time': 'Uhrzeit',
    'meeting_type': 'Meeting-Typ',
    'description': 'Beschreibung',
    'schedule': 'Planen',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'de'; // Default to German as requested
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'de' ? 'en' : 'de');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
